admins/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from admins import views

app_name="admins"

urlpatterns = [

    path('', views.index, name='home'),
    path('users', views.user_page, name="page_user"),
    path('users/<pk>/update', views.UserUpdateView.as_view(), name="update_user"),
    path('users/<pk>/profile', views.UserProfileUpdateView.as_view(), name="update_profile"),
    path('laporan/', views.list_compliant, name="laporan")
]

app/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from app import views
app_name="app"
urlpatterns = [
    # path('',views.dashboard_client, name="client_dashboard"),
    path('page', views.landing_page, name="home"),
    path('laporan/', views.LaporanMasukViewSet.as_view({"get":"list"}), name="laporan-list"),
    path('laporan/create', views.LaporanMasukViewSet.as_view({"put":"create"}), name="laporan-create"),

]

authentication/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path
from .views import login_view, register_user, UserUpdateView, UserProfileUpdateView, UserViewSet
from django.contrib.auth.views import LogoutView
from rest_framework_simplejwt import views as jwt_views

app_name="auth"
urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_user, name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('users/<pk>/update', UserUpdateView.as_view(), name="update_user"),
    path('users/<pk>/profile', UserProfileUpdateView.as_view(), name="update_profile"),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('api/users', UserViewSet.as_view({"get":"list"}), name='user_api_list'),
    path('api/users/<pk>', UserViewSet.as_view({"get":"retrieve"}), name='user_api_retrive'),
    path('api/users/register', UserViewSet.as_view({"post":"create"}), name='user_api_create'),
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve 
def view_404(request, exception=None):
    # make a redirect to homepage
    # you can use the name of url or just the plain link
    return redirect('/home') # or redirect('name-of-index-url')

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("", include("authentication.urls")),  # add this
    path("app/", include("app.urls"), name="app"),  # add this
    path("admin/", include("admins.urls"), name="admin"),
    path('api-auth/', include('rest_framework.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# handler404 = view_404

core/views.py
from django.http import HttpResponse
from django.template import loader

core/templates/includes/navigation.html
    <nav class="pcoded-navbar">
        <div class="navbar-wrapper">
            <div class="navbar-brand header-logo">
                <a target="_blank" href="https://appseed.us/admin-dashboards/django-dashboard-dattaable" class="b-brand">
                    <div class="b-bg">
                        <i class="feather icon-radio"></i>
                    </div>
                    <span class="b-title">Whatsapp hub's</span>
                </a>
                <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
            </div>
            <div class="navbar-content scroll-div">
                {% if request.user.is_superuser %}
                    {% include "includes/navigation_admin.html" %}
                {% elif request.user.is_superuser == False %}
                    {% include "includes/navigation_client.html" %}
                {% endif %}
            </div>
        </div>
    </nav>

core/templates/includes/navigation_admin.html
<ul class="nav pcoded-inner-navbar">
    <li class="nav-item pcoded-menu-caption">
        <label>Navigation</label>
    </li>
    <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
        class="nav-item {% if 'index' in segment %} active {% endif %}">
        <a href="/admin" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span>
            <span class="pcoded-mtext">Dashboard</span></a>
    </li>
    <li data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds" class="nav-item pcoded-hasmenu">
        <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-file-text"></i></span><span class="pcoded-mtext">Management</span></a>
        <ul class="pcoded-submenu">
            <li class=""><a href="{% url 'admins:page_user' %}" class="">User</a></li>
        </ul>
    </li>
    <li data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds" class="nav-item pcoded-hasmenu">
        <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-user"></i></span><span class="pcoded-mtext">Setting</span></a>
        <ul class="pcoded-submenu">
            <li class=""><a href="{% url 'auth:update_user' request.user.id %}" class="">Account</a></li>
            <li class=""><a href="{% url 'auth:update_profile' request.user.id %}" class="">Profile</a></li>
            
        </ul>
    </li>
    
    <li data-username="Disabled Menu" class="nav-item">
        <a href={% url 'auth:logout' %} class="nav-link">
            <span class="pcoded-micon">
                <i class="feather icon-power"></i>
            </span>
            <span class="pcoded-mtext">Logout - [ {{ request.user.username }} ]</span>
        </a>
    </li>
</ul>

core/templates/includes/navigation_client.html
<ul class="nav pcoded-inner-navbar">
    <li class="nav-item pcoded-menu-caption">
        <label>Navigation</label>
    </li>
    <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
        class="nav-item {% if 'index' in segment %} active {% endif %}">
        <a href="{% url 'app:client_dashboard' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span>
            <span class="pcoded-mtext">Dashboard</span></a>
    </li>
    <li data-username="Disabled Menu" class="nav-item">
        <a href="{% url 'app:app_list' %}" class="nav-link">
            <span class="pcoded-micon">
                <i class="feather icon-activity"></i>
            </span>
            <span class="pcoded-mtext">Application List</span>
        </a>
    </li>
    <li data-username="Disabled Menu" class="nav-item">
        <a href="{% url 'sales:invoice_list' %}" class="nav-link">
            <span class="pcoded-micon">
                <i class="feather icon-credit-card"></i>
            </span>
            <span class="pcoded-mtext">Invoice</span>
        </a>
    </li>
    <li data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds" class="nav-item pcoded-hasmenu">
        <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-user"></i></span><span class="pcoded-mtext">Setting</span></a>
        <ul class="pcoded-submenu">
            <li class=""><a href="{% url 'auth:update_user' request.user.id %}" class="">Account</a></li>
            <li class=""><a href="{% url 'auth:update_profile' request.user.id %}" class="">Profile</a></li>
            
        </ul>
    </li>
    <li data-username="Disabled Menu" class="nav-item">
        <a href={% url 'auth:logout' %} class="nav-link">
            <span class="pcoded-micon">
                <i class="feather icon-power"></i>
            </span>
            <span class="pcoded-mtext">Logout - [ {{ request.user.username }} ]</span>
        </a>
    </li>
</ul>

core/templates/includes/scripts.html
    <!-- Required Js -->
    <script src="/static/assets/js/vendor-all.min.js"></script>
    <script src="/static/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/assets/js/pcoded.min.js"></script>