app/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from app import views
app_name="app"
urlpatterns = [
    # path('',views.dashboard_client, name="client_dashboard"),
    path('page', views.landing_page, name="home"),
    path('laporan/', views.LaporanMasukViewSet.as_view({"get":"list"}), name="laporan-list"),
    path('laporan/create', views.LaporanMasukViewSet.as_view({"put":"create"}), name="laporan-create"),

]

authentication/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path
from .views import login_view, register_user, UserUpdateView, UserProfileUpdateView, UserViewSet
from django.contrib.auth.views import LogoutView
from rest_framework_simplejwt import views as jwt_views

app_name="auth"
urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_user, name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('users/<pk>/update', UserUpdateView.as_view(), name="update_user"),
    path('users/<pk>/profile', UserProfileUpdateView.as_view(), name="update_profile"),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('api/users', UserViewSet.as_view({"get":"list"}), name='user_api_list'),
    path('api/users/<pk>', UserViewSet.as_view({"get":"retrieve"}), name='user_api_retrive'),
    path('api/users/register', UserViewSet.as_view({"post":"create"}), name='user_api_create'),
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve 
def view_404(request, exception=None):
    # make a redirect to homepage
    # you can use the name of url or just the plain link
    return redirect('/home') # or redirect('name-of-index-url')

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("", include("authentication.urls")),  # add this
    path("app/", include("app.urls"), name="app"),  # add this
    path("admin/", include("admins.urls"), name="admin"),
    path('api-auth/', include('rest_framework.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# handler404 = view_404

core/views.py
from django.http import HttpResponse
from django.template import loader

core/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}   

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather icon-unlock auth-icon"></i>
                    </div>
                    <h3 class="mb-4">Login</h3>

                    <span class="mb-0 text-muted">
                        {% if msg %}
                            {{ msg | safe }}
                        {% else %}
{#                            Default Credentials: test / ApS12_ZZs8#}
                        {% endif %} 
                    </span>

                    <br />
                    <br />

                    <form role="form" method="post" action="">

                        {% csrf_token %}                   

                        <div class="input-group mb-3">
                            {{ form.username }}
                        </div>
                        
                        <div class="input-group mb-4">
                            {{ form.password }}
                        </div>
                        
                        <div class="form-group text-left">
                            <div class="checkbox checkbox-fill d-inline">
                                <input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-a1" checked="">
                                <label for="checkbox-fill-a1" class="cr"> Save Details</label>
                            </div>
                        </div>
                        <button type="submit" name="login" class="btn btn-primary shadow-2 mb-4">Login</button>

                    </form>

                    <p class="mb-0 text-muted">Don’t have an account? <a href={% url 'auth:register' %} >Signup</a></p>
                    <br />
{#                    <p class="mb-2 text-muted">#}
{#                        &copy; <a target="_blank" href="https://codedthemes.com/">CodedThemes</a> #}
{#                        - <a target="_blank" href="https://appseed.us/admin-dashboards/django-dashboard-dattaable">Django Dashboard DattaAble</a>.#}
{#                    </p>#}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

core/templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}   

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather icon-user-plus auth-icon"></i>
                    </div>
                    <h3 class="mb-4">Sign up</h3>

                    <span class="mb-0 text-muted">
                        {% if msg %}
                            {{ msg | safe }}
                        {% else %}
                            Add your credentials
                        {% endif %} 
                    </span>

                    <br />
                    <br />

                    <form role="form" method="post" action="">

                        {% csrf_token %}                    

                        <div class="input-group mb-3">
                            {{ form.username }}
                        </div>
                        <span class="text-error">{{ form.username.errors }}</span>

                        <div class="input-group mb-3">
                            {{ form.email }}
                        </div>
                        <span class="text-error">{{ form.email.errors }}</span>

                        <div class="input-group mb-4">
                            {{ form.password1 }}
                        </div>
                        <span class="text-error">{{ form.password1.errors }}</span>

                        <div class="input-group mb-4">
                            {{ form.password2 }}
                        </div>
                        <span class="text-error">{{ form.password2.errors }}</span>
                        
                        <div class="form-group text-left">
                            <div class="checkbox checkbox-fill d-inline">
                                <input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-a1" checked="">
                                <label for="checkbox-fill-a1" class="cr"> Agree with <a href="#">terms</a></label>
                            </div>
                        </div>
                        <button type="submit" name="register" class="btn btn-primary shadow-2 mb-4">Register</button>

                    </form>

                    <p class="mb-0 text-muted">Already have an account? <a href="{% url 'auth:login' %}" >Login</a></p>
                    <br />
{#                    <p class="mb-2 text-muted">#}
{#                        &copy; <a target="_blank" href="https://codedthemes.com/">CodedThemes</a> #}
{#                        - <a target="_blank" href="https://appseed.us/admin-dashboards/django-dashboard-dattaable">Django Dashboard DattaAble</a>#}
{#                    </p>#}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}